package us.fyndr.api.admin.dto;

import java.time.Instant;
import java.util.Objects;

import us.fyndr.api.admin.dbo.AccountStatus;

/**
 * . IndividualOutDto Class present the details of individual along with its
 * business details as an output data
 */
public final class IndividualOutDTO {

    /**
     * . The address of a user
     */
    private AddressOutDTO address;

    /**
     * . The account creation date of a user
     */
    private Instant createDt;

    /**
     * . The name of user
     */
    private String name;

    /**
     * . The account status of a user
     */
    private AccountStatus status;

    /**
     * . The isBusiness variable accepts true or false isBusiness checks if a user
     * is an individual user or a business user
     */
    private Boolean isBusiness;

    /**
     * . The business name
     */
    private String businessName;

    /**
     * . The business website
     */
    private String website;

    /**
     * . The phone number of a user
     */
    private PhoneNumberOutDTO phone;

    /**
     * The email of a user.
     */
    private String email;

    /**
     * The autogenerated objId.
     */
    private Long objId;

    /**
     * @return the userId
     */
    public Long getObjId() {
        return objId;
    }

    /**
     * @param userId the userId to set
     */
    public void setObjId(final Long userId) {
        this.objId = userId;
    }

    /**
     * @return account creation date of a user
     */
    public Instant getCreateDt() {
        return createDt;
    }

    /**
     * @param createDt sets the account creation date of a user
     */
    public void setCreateDt(final Instant createDt) {
        this.createDt = createDt;
    }

    /**
     * @return the address of a user
     */
    public AddressOutDTO getAddress() {
        return address;
    }

    /**
     * @param address sets address of a user
     */
    public void setAddress(final AddressOutDTO address) {
        this.address = address;
    }

    /**
     * @return the name of user
     */
    public String getName() {
        return name;
    }

    /**
     * @param name sets the name of user
     */
    public void setName(final String name) {
        this.name = name;
    }

    /**
     * @return the account status of user
     */
    public AccountStatus getStatus() {
        return status;
    }

    /**
     * @param status sets account status of a user
     */
    public void setStatus(final AccountStatus status) {
        this.status = status;
    }

    /**
     * @return the business name
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * @param businessName sets the business name
     */
    public void setBusinessName(final String businessName) {
        this.businessName = businessName;
    }

    /**
     * @return the business website
     */
    public String getWebsite() {
        return website;
    }

    /**
     * @param website sets the business website
     */
    public void setWebsite(final String website) {
        this.website = website;
    }

    /**
     * @return the phonenumber of a user
     */
    public PhoneNumberOutDTO getPhone() {
        return phone;
    }

    /**
     * @param phone sets the phonenumber of a user
     */
    public void setPhone(final PhoneNumberOutDTO phone) {
        this.phone = phone;
    }

    /**
     * @return isbusiness
     */
    public Boolean isBusiness() {
        return isBusiness;
    }

    /**
     * @param isBusiness sets isbusiness
     */
    public void setIsBusiness(final Boolean isBusiness) {
        this.isBusiness = isBusiness;
    }

    /**
     * @return the email of a user
     */
    public String getEmail() {
        return email;
    }

    /**
     * @param email sets the email of a user
     */
    public void setEmail(final String email) {
        this.email = email;
    }

    /**
     * The hashcode method.
     */
    @Override
    public int hashCode() {
        return Objects.hash(objId, address, businessName, createDt, email, isBusiness, name, phone, status, website);
    }

    /**
     * The equals method.
     */
    @Override
    public boolean equals(final Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof IndividualOutDTO)) {
            return false;
        }
        IndividualOutDTO other = (IndividualOutDTO) obj;
        return Objects.equals(address, other.address) && Objects.equals(businessName, other.businessName)
                && Objects.equals(createDt, other.createDt) && Objects.equals(email, other.email)
                && Objects.equals(isBusiness, other.isBusiness) && Objects.equals(name, other.name)
                && Objects.equals(phone, other.phone) && status == other.status
                && Objects.equals(website, other.website) && Objects.equals(objId, other.objId);
    }

    /**
     * The toString method.
     */
    @Override
    public String toString() {
        return "IndividualOutDTO [objId=" + objId + ", address=" + address + ", createDt=" + createDt + ", "
                + "name=" + name + ", status=" + status + ", isBusiness=" + isBusiness + ", businessName="
                + businessName + ", website=" + website + ", phone=" + phone + ", email=" + email + "]";
    }
}

