server:
    port: 8084

logging.level.org.springframework.boot.autoconfigure: ERROR

spring.main.lazy-initialization: true

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS: false

cloud.aws.stack.auto: false
cloud.aws.region.static: us-west-1

#spring.application.name: fyndr-dev

spring.datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PGHOST}:5432/${PGDATABASE}?currentSchema=${PGSCHEMA}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    hikari:
        maximum-pool-size: 30
        minimum-idle: 5
        idle-timeout: 60000
        
feign.hystrix.enabled: true
hystrix.command.default.execution.timeout.enabled: false
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

hystrix:
  threadpool:
    default:
      coreSize: 20
      maximumSize: 100
      maxQueueSize: 80

graph:
  url: ${graph_update_url}
  
token:
  url: ${token-service-url}

notification:
  image:
    base:
      url: ${web_bucket_name}
  
sns:
  topic:
    arn: ${topic_to_notify}

logging.level.com.amazonaws.util.EC2MetadataUtils: error
logging.level.com.amazonaws.internal.InstanceMetadataServiceResourceFetcher: error