package us.fyndr.api.admin.dbo;

import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.springframework.data.rest.core.annotation.Description;

/**
 * . Business class contains business level information of an individual
 */
@Entity
@Table(name = "biz_master")
public class Business {

    /**
     * The Autogenerated objId.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "objid")
    private Long objId;

    /**
     * . The Business Name
     */
    @Description(value = "Business Name")
    @Column(name = "biz_name", unique = true)
    private String businessName;

    /**
     * The Type of Business.
     */
    @Description(value = "Business Type")
    @Column(name = "biz_type")
    private String bizType;

    /**
     * . The Business Website
     */
    @Description(value = "Website of business")
    @Column(name = "website", unique = true)
    private String website;

    /**
     * @return ObjId
     */
    public Long getObjId() {
        return objId;
    }

    /**
     * @param objid Setter function to set ObjId
     */
    public void setObjId(final Long objid) {
        this.objId = objid;
    }

    /**
     * @return the business name
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * @param businessName sets the business name
     */
    public void setBusinessName(final String businessName) {
        this.businessName = businessName;
    }

    /**
     * @return the business website
     */
    public String getWebsite() {
        return website;
    }

    /**
     * @param website sets the business website
     */
    public void setWebsite(final String website) {
        this.website = website;
    }

    /**
     * @return Business type of user
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * @param bizType Setter method to set business type of user
     */
    public void setBizType(final String bizType) {
        this.bizType = bizType;
    }

    /**
     * . The hash code method
     */
    @Override
    public int hashCode() {
        return Objects.hash(businessName, objId, website, bizType);
    }

    /**
     * . The equals method
     */
    @Override
    public boolean equals(final Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof Business)) {
            return false;
        }
        Business other = (Business) obj;
        return Objects.equals(businessName, other.businessName) && Objects.equals(objId, other.objId)
                && Objects.equals(website, other.website) && Objects.equals(bizType, other.bizType);
    }

    /**
     * . The toString method
     */
    @Override
    public String toString() {
        return "Business [objId=" + objId + ", businessName=" + businessName + ", "
                + "bizType=" + bizType + ", website=" + website + "]";
    }

}
