package us.fyndr.api.admin.dbo;

import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.ConstructorResult;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.Table;

import us.fyndr.api.admin.model.CountCampaignOffers;

/**
 * @author bisen Campaign Offer.
 *
 */
@SqlResultSetMapping(name = "CountCampaignOffers", classes = {
        @ConstructorResult(targetClass = CountCampaignOffers.class, columns = {
                @ColumnResult(name = "activeOffer", type = Integer.class),
                @ColumnResult(name = "totalOffer", type = Integer.class),
                @ColumnResult(name = "offerSold", type = Integer.class), }) })
@Entity
@Table(name = "cmpn_offer")
public class CampaignOffer {

    /**
     * The Autogenerated objId.
     */
    @Id
    @Column(name = "objid")
    private Long objId;

    /**
     * The Offer Sold.
     */
    @Column(name = "offer_sold")
    private Integer offerSold;

    /**
     * The Offer Sold.
     */
    @Column(name = "cmpn_id")
    private Long campaignId;

    /**
     * The Status.
     */
    @Column(name = "status")
    private String status;

    /**
     * The Currency.
     */
    private String currency;

    /**
     * The Currency Symbol.
     */
    private String currencySymbol;

    /**
     * @return the currency
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * @param currency the currency to set
     */
    public void setCurrency(final String currency) {
        this.currency = currency;
    }

    /**
     * @return the currencySymbol
     */
    public String getCurrencySymbol() {
        return currencySymbol;
    }

    /**
     * @param currencySymbol the currencySymbol to set
     */
    public void setCurrencySymbol(final String currencySymbol) {
        this.currencySymbol = currencySymbol;
    }

    /**
     * @return the campaignId
     */
    public Long getCampaignId() {
        return campaignId;
    }

    /**
     * @param campaignId the campaignId to set
     */
    public void setCampaignId(final Long campaignId) {
        this.campaignId = campaignId;
    }

    /**
     * @return the offerSold
     */
    public Integer getOfferSold() {
        return offerSold;
    }

    /**
     * @param offerSold the offerSold to set
     */
    public void setOfferSold(final Integer offerSold) {
        this.offerSold = offerSold;
    }

    /**
     * @return the objId
     */
    public Long getObjId() {
        return objId;
    }

    /**
     * @param objId the objId to set
     */
    public void setObjId(final Long objId) {
        this.objId = objId;
    }

    /**
     * @return the status
     */
    public String getStatus() {
        return status;
    }

    /**
     * @param status the status to set
     */
    public void setStatus(final String status) {
        this.status = status;
    }

    /**
     * the hashcode method.
     */
    @Override
    public int hashCode() {
        return Objects.hash(campaignId, currency, currencySymbol, objId, offerSold, status);
    }

    /**
     * the equals method.
     */
    @Override
    public boolean equals(final Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof CampaignOffer)) {
            return false;
        }
        CampaignOffer other = (CampaignOffer) obj;
        return Objects.equals(campaignId, other.campaignId) && Objects.equals(currency, other.currency)
                && Objects.equals(currencySymbol, other.currencySymbol) && Objects.equals(objId, other.objId)
                && Objects.equals(offerSold, other.offerSold) && Objects.equals(status, other.status);
    }

    /**
     * the toString method.
     */
    @Override
    public String toString() {
        return "CampaignOffer [objId=" + objId + ", offerSold=" + offerSold + ", campaignId=" + campaignId + ", status="
                + status + ", currency=" + currency + ", currencySymbol=" + currencySymbol + "]";
    }

}
