package us.fyndr.api.admin.dbo;

import java.time.Instant;
import java.util.Objects;
import javax.persistence.ColumnResult;
import javax.persistence.ConstructorResult;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.Table;

import org.springframework.data.rest.core.annotation.Description;

import us.fyndr.api.admin.model.CampaignDetails;

/**
 * @author saksh Campaign Table contains the information regarding the campaign
 *         created by business user.
 */

@SqlResultSetMapping(name = "CampaignDetails", classes = {
        @ConstructorResult(targetClass = CampaignDetails.class, columns = {
                @ColumnResult(name = "cmpnId", type = Integer.class),
                @ColumnResult(name = "buisnessName", type = String.class),
                @ColumnResult(name = "campaignName", type = String.class),
                @ColumnResult(name = "buisnessType", type = String.class),
                @ColumnResult(name = "campaignType", type = String.class),
                @ColumnResult(name = "totalOfferSoldAmount", type = Double.class),
                @ColumnResult(name = "endDate", type = Instant.class),
                }) })
@Entity
@Table(name = "cmpn")
public class Campaign {

    /**
     * The Autogenerated objId.
     */
    @Id
    @Column(name = "objid")
    private Long objId;

    /**
     * The goal of a campaign. Values can be - online, instore, all.
     */
    @Column(name = "goal")
    private String goal;

    /**
     * The status of a campaign. Values can be - active, expired.
     */
    @Column(name = "status")
    private String status;

    /**
     * The Business Id.
     */
    @Description(value = "Business ID")
    @Column(name = "bizid")
    private Long businessId;

    /**
     * The Campaign Type which define type of campaign.
     */
    @Column(name = "cmpn_type")
    private String campaignType;

    /**
     * The Campaign Type which define type of campaign.
     */
    @Column(name = "title")
    private String title;

    /**
     * The account end date of a user.
     */
    @Description(value = "End date")
    @Column(name = "end_dt")
    private Instant endDate;

    /**
     * @return the objId
     */
    public Long getObjId() {
        return objId;
    }

    /**
     * @param objId sets the objId
     */
    public void setObjId(final Long objId) {
        this.objId = objId;
    }

    /**
     * @return the goal
     */
    public String getGoal() {
        return goal;
    }

    /**
     * @param goal sets the goal
     */
    public void setGoal(final String goal) {
        this.goal = goal;
    }

    /**
     * @return the status
     */
    public String getStatus() {
        return status;
    }

    /**
     * @param status sets the status
     */
    public void setStatus(final String status) {
        this.status = status;
    }

    /**
     * @return the title
     */
    public String getTitle() {
        return title;
    }

    /**
     * @param title the title to set
     */
    public void setTitle(final String title) {
        this.title = title;
    }

    /**
     * @return the businessId
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * @param businessId the businessId to set
     */
    public void setBusinessId(final Long businessId) {
        this.businessId = businessId;
    }

    /**
     * @return the campaignType
     */
    public String getCampaignType() {
        return campaignType;
    }

    /**
     * @param campaignType the campaignType to set
     */
    public void setCampaignType(final String campaignType) {
        this.campaignType = campaignType;
    }

    /**
     * @return the endDate
     */
    public Instant getEndDate() {
        return endDate;
    }

    /**
     * @param endDate the endDate to set
     */
    public void setEndDate(final Instant endDate) {
        this.endDate = endDate;
    }

    /**
     * The toString method.
     */
    @Override
    public String toString() {
        return "Campaign [objId=" + objId + ", goal=" + goal + ", status=" + status + ", businessId=" + businessId
                + ", campaignType=" + campaignType + ", title=" + title + ", endDate=" + endDate + "]";
    }

    /**
     * The hascode method.
     */
    @Override
    public int hashCode() {
        return Objects.hash(businessId, campaignType, endDate, goal, objId, status, title);
    }

    /**
     * The equals method.
     */
    @Override
    public boolean equals(final Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof Campaign)) {
            return false;
        }
        Campaign other = (Campaign) obj;
        return Objects.equals(businessId, other.businessId) && Objects.equals(campaignType, other.campaignType)
                && Objects.equals(endDate, other.endDate) && Objects.equals(goal, other.goal)
                && Objects.equals(objId, other.objId) && Objects.equals(status, other.status)
                && Objects.equals(title, other.title);
    }
}
