package us.fyndr.api.admin.dbo;

import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CodeMaster is the DBO class for code_master table. It stores the unique qrid
 * corresponding to every user.
 */
@Entity
@Table(name = "code_master")
public class CodeMaster {

    /**
     * The Autogenerated objId.
     */
    @Id
    @Column(name = "objid")
    private Long objId;

    /**
     * @return the objid
     */
    public Long getObjId() {
        return objId;
    }

    /**
     * @param objid the objid to set
     */
    public void setObjId(final Long objid) {
        this.objId = objid;
    }

    /**
     * The toString Method.
     */
    @Override
    public String toString() {
        return "CodeMaster [objId=" + objId + "]";
    }

    /**
     * The hashCode method.
     */
    @Override
    public int hashCode() {
        return Objects.hash(objId);
    }

    /**
     * The equals method.
     */
    @Override
    public boolean equals(final Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof CodeMaster)) {
            return false;
        }
        CodeMaster other = (CodeMaster) obj;
        return Objects.equals(objId, other.objId);
 }

}
